spring:
  application:
    name: portifolio
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-ancient-moon-acagu8o9.sa-east-1.aws.neon.tech/neondb?sslmode=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_nLPrwjy1mK4b}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: ${SHOW_SQL:false}
    open-in-view: false

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-message: always

portfolio:
  admin:
    secret-key: ${ADMIN_SECRET_KEY:admin123}
